👷 Disable AMD build

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -196,90 +196,90 @@ jobs:
           provenance: false
           tags: ${{ env.TAGS }}
 
-  amd-base:
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        build:
-          - {latest: "false", comfyui: "v0.8.2", python: "3.12", pytorch: "2.9.1", rocm: "6.0-runtime"}
-    steps:
-      -
-        name: Free Space
-        run: |
-          df -h
-          sudo rm -rf /usr/share/dotnet
-          sudo rm -rf /opt/ghc
-          sudo rm -rf /usr/local/.ghcup
-          sudo rm -rf /usr/local/share/boost
-          sudo rm -rf /usr/local/lib/android
-          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
-          df -h
-      -
-        name: Env Setter
-        run: |
-          REPO=${GITHUB_REPOSITORY,,}
-          echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
-          echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
-      -
-        name: Checkout
-        uses: actions/checkout@v4
-      -
-        name: Permissions fixes
-        run: |
-          target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
-          chmod -R ug+rwX ${target}
-      #-
-      #  name: Login to DockerHub
-      #  uses: docker/login-action@v3
-      #  with:
-      #    username: ${{ vars.DOCKERHUB_USER }}
-      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Login to GitHub Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      -
-        name: Set tags
-        run: |
-            img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
-            img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-rocm"
-            if [[ -z '${{ matrix.build.comfyui }}' ]]; then
-                COMFYUI_BUILD_REF="$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/tags | jq -r '.[0].name')"
-            else
-                COMFYUI_BUILD_REF="${{ matrix.build.comfyui }}"
-            fi
-            [ -z "$COMFYUI_BUILD_REF" ] && { echo "Error: COMFYUI_BUILD_REF is empty. Exiting script." >&2; exit 1; }
-            echo "COMFYUI_BUILD_REF=${COMFYUI_BUILD_REF}" >> ${GITHUB_ENV}
+  # amd-base:
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       build:
+  #         - {latest: "false", comfyui: "v0.8.2", python: "3.12", pytorch: "2.9.1", rocm: "6.0-runtime"}
+  #   steps:
+  #     -
+  #       name: Free Space
+  #       run: |
+  #         df -h
+  #         sudo rm -rf /usr/share/dotnet
+  #         sudo rm -rf /opt/ghc
+  #         sudo rm -rf /usr/local/.ghcup
+  #         sudo rm -rf /usr/local/share/boost
+  #         sudo rm -rf /usr/local/lib/android
+  #         sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+  #         df -h
+  #     -
+  #       name: Env Setter
+  #       run: |
+  #         REPO=${GITHUB_REPOSITORY,,}
+  #         echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
+  #         echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
+  #     -
+  #       name: Checkout
+  #       uses: actions/checkout@v4
+  #     -
+  #       name: Permissions fixes
+  #       run: |
+  #         target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
+  #         chmod -R ug+rwX ${target}
+  #     #-
+  #     #  name: Login to DockerHub
+  #     #  uses: docker/login-action@v3
+  #     #  with:
+  #     #    username: ${{ vars.DOCKERHUB_USER }}
+  #     #    password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #     -
+  #       name: Login to GitHub Container Registry
+  #       uses: docker/login-action@v3
+  #       with:
+  #         registry: ghcr.io
+  #         username: ${{ github.actor }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
+  #     -
+  #       name: Set tags
+  #       run: |
+  #           img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
+  #           img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-rocm"
+  #           if [[ -z '${{ matrix.build.comfyui }}' ]]; then
+  #               COMFYUI_BUILD_REF="$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/tags | jq -r '.[0].name')"
+  #           else
+  #               COMFYUI_BUILD_REF="${{ matrix.build.comfyui }}"
+  #           fi
+  #           [ -z "$COMFYUI_BUILD_REF" ] && { echo "Error: COMFYUI_BUILD_REF is empty. Exiting script." >&2; exit 1; }
+  #           echo "COMFYUI_BUILD_REF=${COMFYUI_BUILD_REF}" >> ${GITHUB_ENV}
 
-            base_tag="v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}"
+  #           base_tag="v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}"
 
-            TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}"
-            if [[ ${{ matrix.build.latest }} == "true" ]]; then
-                TAGS="${TAGS}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
-            fi
+  #           TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}"
+  #           if [[ ${{ matrix.build.latest }} == "true" ]]; then
+  #               TAGS="${TAGS}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
+  #           fi
 
-            if [[ -n "${{ vars.DOCKERHUB_USER }}" ]]; then
-                TAGS="${TAGS}, ${img_path_dhub}:${COMFYUI_BUILD_REF}"
-                if [[ ${{ matrix.build.latest }} == "true" ]]; then
-                    TAGS="${TAGS}, ${img_path_dhub}:latest"
-                fi
-            fi
+  #           if [[ -n "${{ vars.DOCKERHUB_USER }}" ]]; then
+  #               TAGS="${TAGS}, ${img_path_dhub}:${COMFYUI_BUILD_REF}"
+  #               if [[ ${{ matrix.build.latest }} == "true" ]]; then
+  #                   TAGS="${TAGS}, ${img_path_dhub}:latest"
+  #               fi
+  #           fi
             
-            echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
-      -
-        name: Build and push
-        uses: docker/build-push-action@v5
-        with:
-          context: build
-          build-args: |
-            IMAGE_BASE=ghcr.io/momentfactory/ai-dock-python:${{ matrix.build.python }}-v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}
-            PYTHON_VERSION=${{ matrix.build.python }}
-            PYTORCH_VERSION=${{ matrix.build.pytorch }}
-            COMFYUI_BUILD_REF=${{ env.COMFYUI_BUILD_REF }}
-          push: true
-          provenance: false
-          tags: ${{ env.TAGS }}
+  #           echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
+  #     -
+  #       name: Build and push
+  #       uses: docker/build-push-action@v5
+  #       with:
+  #         context: build
+  #         build-args: |
+  #           IMAGE_BASE=ghcr.io/momentfactory/ai-dock-python:${{ matrix.build.python }}-v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}
+  #           PYTHON_VERSION=${{ matrix.build.python }}
+  #           PYTORCH_VERSION=${{ matrix.build.pytorch }}
+  #           COMFYUI_BUILD_REF=${{ env.COMFYUI_BUILD_REF }}
+  #         push: true
+  #         provenance: false
+  #         tags: ${{ env.TAGS }}
